version: '3.7'

services:
  front:
    container_name: marathon-front
    restart: always
    build:
        context: .
        args:
          NEXT_PUBLIC_DEFAULT_LOCALE: ${NEXT_PUBLIC_DEFAULT_LOCALE}
          NEXT_PUBLIC_GRAPHQL_URI: ${NEXT_PUBLIC_GRAPHQL_URI}
          NEXT_PUBLIC_STATUS_URI: ${NEXT_PUBLIC_STATUS_URI}
          NEXT_PUBLIC_UNITY_PUBLIC_FOLDER: ${NEXT_PUBLIC_UNITY_PUBLIC_FOLDER}
          NEXT_PUBLIC_UNITY_BUILD_NAME: ${NEXT_PUBLIC_UNITY_BUILD_NAME}
          NEXT_PUBLIC_UNITY_COMPANY_NAME: ${NEXT_PUBLIC_UNITY_COMPANY_NAME}
          NEXT_PUBLIC_UNITY_PRODUCT_NAME: ${NEXT_PUBLIC_UNITY_PRODUCT_NAME}
          NEXT_PUBLIC_UNITY_PRODUCT_VERSION: ${NEXT_PUBLIC_UNITY_PRODUCT_VERSION}
          NEXT_PUBLIC_UNITY_PUBLIC_MEDIA_URI: ${NEXT_PUBLIC_UNITY_PUBLIC_MEDIA_URI}
          NEXT_PUBLIC_UNITY_ASSET_BUNDLE_FOLDER: ${NEXT_PUBLIC_UNITY_ASSET_BUNDLE_FOLDER}
          NEXT_PUBLIC_UNITY_DEFAULT_PLATFORM: ${NEXT_PUBLIC_UNITY_DEFAULT_PLATFORM}
          NEXT_PUBLIC_UNITY_MODULE_MATERIALS_FOLDER: ${NEXT_PUBLIC_UNITY_MODULE_MATERIALS_FOLDER}
          NEXT_PUBLIC_UNITY_MANIFEST_ASSET_NAME: ${NEXT_PUBLIC_UNITY_MANIFEST_ASSET_NAME}
          NEXT_PUBLIC_MARATHON_API: ${NEXT_PUBLIC_MARATHON_API}
          NEXT_PUBLIC_MARATHON_API_LIST: ${NEXT_PUBLIC_MARATHON_API_LIST}
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
